name: Publish to NPM

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        registry-url: 'https://registry.npmjs.org'
        cache: 'npm'

    - name: Install dependencies
      run: |
        if [ -f package-lock.json ]; then
          echo "Found package-lock.json, using npm ci"
          npm ci
        else
          echo "No package-lock.json found, using npm install"
          npm install
        fi

    - name: Run tests
      run: npm test

    - name: Test API connectivity
      run: npm run test:api
      continue-on-error: true

    - name: Verify package contents
      run: |
        echo "Package contents that will be published:"
        npm pack --dry-run
        echo "Package version:"
        node -p "require('./package.json').version"

    - name: Publish to NPM
      run: npm publish --provenance
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
